
blank_issues_enabled: false
contact_links:
  - name: Feature request or Idea
    url: https://github.com/FirstGearGames/FishNet/discussions/categories/ideas
    about: Suggest an idea for this project.
  - name: Question
    url: https://github.com/FirstGearGames/FishNet/discussions/categories/q-a
    about: Please ask and answer questions here.
